name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v ./...